export const cardItems = [
  {
    company: "WHO studio",
    title: "Banking",
    badge: "Phone Interview",
    text: "Cologne, North Rhine-Westphalia, Germany",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Accepted",
    tag2Text: "Academic Issues",
    tag1TextCol: "#59AA1A",
    tag1Col: "success",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Administrative Assistant Secretary",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Accepted",
    tag2Text: "Academic Issues",
    tag1TextCol: "#59AA1A",
    tag1Col: "success",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Administrative Coordinator",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Phone Interview",
    tag2Text: "Academic Issues",
    tag1TextCol: "#9424BC",
    tag1Col: "purple",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Administrative Assistant Secretary",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Unassigned",
    tag2Text: "Academic Issues",
    tag1TextCol: "#3686E4",
    tag1Col: "processing",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Banking",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Rejected",
    tag2Text: "Academic Issues",
    tag1TextCol: "#E30613",
    tag1Col: "error",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Banking",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "1st Person Interview",
    tag2Text: "Academic Issues",
    tag1TextCol: "#FCBD06",
    tag1Col: "warning",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Banking",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "2nd Person Interview",
    tag2Text: "Academic Issues",
    tag1TextCol: "#B6DA24",
    tag1Col: "warning",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
  {
    company: "WHO studio",
    title: "Banking",
    text: "Alvarez and Marsal",
    location: "Germany",
    price: "$500.00 - $15,000",
    tag1Text: "Offer",
    tag2Text: "Academic Issues",
    tag1TextCol: "#0754EB",
    tag1Col: "processing",
    tag2TextCol: "",
    tag2Col: "#4E27CD",
    duration: "3 weeks ago",
  },
];

export const cardInfo = [
  { id: "1", desc: "All", title: "72", shadowColor: "#5832DA10" },
  { id: "2", desc: "Unassigned", title: "8", shadowColor: "#3686E4" },
  { id: "3", desc: "Phone Interview", title: "12", shadowColor: "#9424BC" },
  {
    id: "4",
    desc: "1st Person Interview",
    title: "9",
    shadowColor: "#FCBD06",
  },
  {
    id: "5",
    desc: "2nd Person Interview",
    title: "6",
    shadowColor: "#B6DA24",
  },
  { id: "6", desc: "Rejected", title: "4", shadowColor: "#FF4A4A" },
];
